version: '3.3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis

  app:
    build:
      context: .정
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    container_name: ndp