version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    image: minjik0525/ndp-back:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    container_name: ndp

